### PR TITLE
Support for threads on clasp has been upgraded

### PR DESCRIPTION
**Pull request by drmeister**
We've upgraded the thread support on clasp and so these small changes appear to be necessary to bordeaux threads to represent that.

Could you also submit these new changes to quicklisp?

### CODE REVIEW

**Comment by drmeister** [comment]
I'm told these changes are already made.

But quicklisp has not been updated with the latest bordeaux threads.

**Comment by sionescu** [comment]
I'll make a new release.

**Comment by drmeister** [comment]
Oh!  Thank you very much.

**Comment by kpoeck** [comment]
Great!

**Pull request closed without merging**
