### PR TITLE
CCL semaphores now have a count argument

### PR DESCRIPTION
**Pull request by Slids**
I submitted:
https://github.com/Clozure/ccl/pull/310/files
Make semaphore can now just set the count argument.

### CODE REVIEW

**Comment by sionescu** [comment]
Thanks, merged.

**Comment by sionescu** [comment]
Oops, undid that. I'll merge when that commit ends up in a release.

**Comment by sionescu** [comment]
Can you provide a backwards-compatible implementation ? It's usually a matter of figuring out the right reader conditional that matches version <=1.12.0

**Comment by Slids** [comment]
Will do

**Comment by sionescu** [comment]
Any update ?

**Comment by sionescu** [comment]
I merged it as-is.

**Pull request closed without merging**
