### PR TITLE
Add support for lispworks 7

### PR DESCRIPTION
**Pull request by ober**

### CODE REVIEW

**Comment by sionescu** [comment]
Is this all ? Have you run the test suite ?

**Comment by ober** [comment]
I've tested it with actually using it. Will run the test suite now.

**Comment by sionescu** [comment]
Nice, thanks.

**Comment by sionescu** [comment]
Merged, Thanks.

**Comment by ober** [comment]
Test suite passes if you convert all lispworks6 -> lispworks7.
So I'm working on a clean way to add it

**Pull request closed without merging**
